export const PALABRAS = [
    { palabra: "HARRYPOTTER", pista: "El niño mago más famoso de Hogwarts" },
    { palabra: "FROZEN", pista: "Película de Disney donde cantan 'Let it go'" },
    { palabra: "BREAKINGBAD", pista: "Serie del profesor que cocina metanfetamina" },
    { palabra: "THESIMPSONS", pista: "Familia amarilla con Homer y Bart" },
    { palabra: "IRONMAN", pista: "Superhéroe millonario con armadura de acero" },
    { palabra: "SPIDERMAN", pista: "Héroe que lanza telarañas" },
    { palabra: "ELREYLEON", pista: "Película de Disney con Simba y Mufasa" },
    { palabra: "TOYSTORY", pista: "Woody y Buzz son los protagonistas" },
    { palabra: "TITANIC", pista: "Película del barco que se hundió" },
    { palabra: "AVENGERS", pista: "Grupo de superhéroes de Marvel" },
    { palabra: "STRANGERTHINGS", pista: "Serie con niños y el Mundo del Revés" },
    { palabra: "GAMEOFTHRONES", pista: "Serie con dragones y tronos" },
    { palabra: "MICHAELJACKSON", pista: "El Rey del Pop" },
    { palabra: "BEYONCE", pista: "Cantante famosa por 'Single Ladies'" },
    { palabra: "SHAKIRA", pista: "Cantante de Colombia, sus caderas no mienten" },
    { palabra: "BRADPITT", pista: "Actor de Hollywood, ex de Angelina Jolie" },
    { palabra: "ANGELINAJOLIE", pista: "Actriz famosa por 'Maléfica'" },
    { palabra: "LEONARDODICAPRIO", pista: "Ganó un Óscar por 'El Renacido'" },
    { palabra: "SELENAGOMEZ", pista: "Cantante y actriz de Disney" },
    { palabra: "MILEYCYRUS", pista: "Famosa por 'Hannah Montana'" },
    { palabra: "HIGHSCHOOLMUSICAL", pista: "Película de Disney con Troy y Gabriella" },
    { palabra: "ALADDIN", pista: "Película con una lámpara mágica" },
    { palabra: "MOANA", pista: "Película de Disney sobre el océano" },
    { palabra: "ENCANTO", pista: "Película de Disney ambientada en Colombia" },
    { palabra: "COCO", pista: "Película de Disney sobre el Día de Muertos" },
    { palabra: "BLACKPINK", pista: "Grupo de K-Pop femenino muy famoso" },
    { palabra: "BTS", pista: "Grupo de K-Pop masculino conocido mundialmente" },
    { palabra: "JUSTINBIEBER", pista: "Cantante de 'Baby'" },
    { palabra: "TAYLORSWIFT", pista: "Cantante famosa por 'Shake It Off'" },
    { palabra: "ADELE", pista: "Cantante de 'Hello'" },
    { palabra: "RIHANNA", pista: "Cantante de 'Umbrella'" },
    { palabra: "EMINEM", pista: "Rapero de Detroit, conocido como Slim Shady" },
    { palabra: "DWAYNEJOHNSON", pista: "Actor y ex luchador conocido como 'La Roca'" },
    { palabra: "JENNIFERLOPEZ", pista: "Cantante y actriz, también conocida como JLo" },
    { palabra: "MADONNA", pista: "Reina del pop en los 80 y 90" },
    { palabra: "ELSA", pista: "Princesa de Disney con poderes de hielo" },
    { palabra: "MICKEYMOUSE", pista: "El ratón más famoso de Disney" },
    { palabra: "CENICIENTA", pista: "Princesa que perdió un zapato de cristal" },
    { palabra: "MULAN", pista: "Princesa guerrera que se hace pasar por soldado" },
    { palabra: "LACASADEPAPEL", pista: "Serie española con máscaras de Dalí" },
];
